---
- name: Get latest updates
  become: yes
  apt:
      install_recommends: no
      update_cache: yes
      upgrade: dist
- name: Install software
  become: yes
  apt:
      install_recommends: no
      name: "{{ item }}"
      state: latest
  with_items:
      - build-essential
      - curl
      - git
      - inkscape
      - libreoffice
      - python-pip
      - python3
      - python3-pip
      - redshift
      - texlive
      - texlive-latex-extra
      - texlive-latex-recommended
      - texstudio
      - thunderbird
      - vim
      - virtualenv
      - xchat
      - zathura
- name: Remove software
  become: yes
  apt:
      name: "{{ item }}"
      state: absent
      purge: yes
  with_items:
      - firefox-esr
- name: Install SpiderOak
  become: yes
  apt:
      deb: https://spideroak.com/release/spideroak/deb_x64
- name: Check if SpiderOak is already set up
  stat:
      path: ~/.config/SpiderOakONE
  register: spideroak_installed
- name: Create SpiderOak login config
  template:
      src: templates/spideroak.json.j2
      dest: /tmp/spideroak.json
      mode: 0600
  when: not spideroak_installed.stat.isdir
- name: Log in to SpiderOak
  command: SpiderOakONE --setup=/tmp/spideroak.json
  args:
      creates: ~/.config/SpiderOakONE
- name: Remove SpiderOak login config
  file:
      name: /tmp/spideroak.json
      state: absent
- name: Install pyenv
  git:
      depth: 10
      dest: ~/.pyenv
      repo: 'https://github.com/pyenv/pyenv.git'
- name: Install pyenv-virtualenv
  git:
      depth: 10
      dest: ~/.pyenv/plugins/pyenv-virtualenv
      repo: 'https://github.com/pyenv/pyenv-virtualenv'
- name: Install Cargo/Rust
  shell: curl https://sh.rustup.rs -sSf | sh -s -- -y --no-modify-path
  args:
      creates: ~/.cargo
- name: Setup bashrc
  copy:
      src: bashrc
      dest: ~/.bashrc
      mode: 0600
- name: Setup Xdefaults
  copy:
      src: Xdefaults
      dest: ~/.Xdefaults
      mode: 0600
- name: Setup vimrc
  copy:
      src: vimrc
      dest: ~/.vimrc
      mode: 0600
- name: Setup Redshift
  copy:
      src: redshift.conf
      dest: ~/.config/redshift.conf
      mode: 0600
- name: Setup Compose key
  become: yes
  lineinfile:
      path: /etc/default/keyboard
      regexp: 'XKBOPTIONS="*"'
      line: 'XKBOPTIONS="compose:lwin"'
- name: Create vim plugin directory
  file:
      dest: "{{ item }}"
      state: directory
      mode: 0700
      force: yes
  with_items:
      - ~/.vim
      - ~/.vim/autoload
      - ~/.vim/bundle
- name: Install pathogen.vim
  get_url:
      dest: ~/.vim/autoload/pathogen.vim
      url: https://tpo.pe/pathogen.vim
      mode: 0640
- name: Install rust syntax highlighting for vim
  git:
      depth: 10
      dest: ~/.vim/bundle/rust.vim
      repo: 'https://github.com/rust-lang/rust.vim.git'
- name: Install typescript syntax highlighting for vim
  git:
      depth: 10
      dest: ~/.vim/bundle/typescript-vim
      repo: 'https://github.com/leafgarland/typescript-vim.git'
